### PR TITLE
Help to people get started using Logary easier.

### PR DESCRIPTION
**Pull request by Thorium**

### CODE REVIEW

**Comment by haf** [comment]
Thank you! :)

**Comment by Thorium** [comment]
This needs still the run of the build script for updating the site. :-)

**Comment by haf** [comment]
Ran into another tooling bug https://github.com/NuGet/Home/issues/2800

**Comment by Thorium** [comment]
Hmm. That is a NuGet issue but why to use so old version of Fake:
https://www.nuget.org/packages/FAKE/

**Comment by haf** [comment]
Only because that version worked once and we don't do much heavy lifting with it anyway. I'll continue hacking at this in a little while.

**Comment by Thorium** [comment]
Bug seems to be closed now. :-)

**Pull request merged**
